import type { ExpenseWithDetails } from "./types";

const now = new Date();
const today = now.toISOString();
const yesterday = new Date(now.getTime() - 86400000).toISOString();
const twoDaysAgo = new Date(now.getTime() - 2 * 86400000).toISOString();
const threeDaysAgo = new Date(now.getTime() - 3 * 86400000).toISOString();
const fiveDaysAgo = new Date(now.getTime() - 5 * 86400000).toISOString();
const weekAgo = new Date(now.getTime() - 7 * 86400000).toISOString();

export const MOCK_EXPENSES: ExpenseWithDetails[] = [
  {
    id: 101,
    source_event_id: 1,
    amount_minor: 1850,
    currency: "SGD",
    occurred_at_utc: today,
    status: "final",
    description: "Lunch at hawker center",
    text_raw: "lunch at hawker center",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["food","lunch"]',
  },
  {
    id: 102,
    source_event_id: 2,
    amount_minor: 3200,
    currency: "SGD",
    occurred_at_utc: today,
    status: "needs_review",
    description: "Grab to office",
    text_raw: "grab to office",
    r2_object_key: null,
    needs_review_reason: true,
    message_type: "text" as const,
    transcript: null,
    tags: '["transport"]',
  },
  {
    id: 103,
    source_event_id: 3,
    amount_minor: 5500,
    currency: "SGD",
    occurred_at_utc: yesterday,
    status: "final",
    description: "Dinner with friends",
    text_raw: "dinner with friends",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["food","entertainment"]',
  },
  {
    id: 104,
    source_event_id: 4,
    amount_minor: 12900,
    currency: "SGD",
    occurred_at_utc: yesterday,
    status: "final",
    description: "Uniqlo t-shirts",
    text_raw: null,
    r2_object_key: "receipts/104.jpg",
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["shopping"]',
  },
  {
    id: 105,
    source_event_id: 5,
    amount_minor: 2400,
    currency: "SGD",
    occurred_at_utc: twoDaysAgo,
    status: "final",
    description: "MRT top up",
    text_raw: "mrt top up",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["transport"]',
  },
  {
    id: 106,
    source_event_id: 6,
    amount_minor: 150000,
    currency: "SGD",
    occurred_at_utc: threeDaysAgo,
    status: "final",
    description: "Rent - March",
    text_raw: "rent march",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["bills","rent"]',
  },
  {
    id: 107,
    source_event_id: 7,
    amount_minor: 4500,
    currency: "SGD",
    occurred_at_utc: threeDaysAgo,
    status: "final",
    description: "Movie tickets",
    text_raw: "movie tickets",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["entertainment"]',
  },
  {
    id: 108,
    source_event_id: 8,
    amount_minor: 8500,
    currency: "SGD",
    occurred_at_utc: fiveDaysAgo,
    status: "final",
    description: "GP clinic visit",
    text_raw: "clinic visit",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["health"]',
  },
  {
    id: 109,
    source_event_id: 9,
    amount_minor: 3800,
    currency: "SGD",
    occurred_at_utc: weekAgo,
    status: "final",
    description: "Grocery run at FairPrice",
    text_raw: "grocery run",
    r2_object_key: null,
    needs_review_reason: false,
    message_type: "text" as const,
    transcript: null,
    tags: '["groceries"]',
  },
  {
    id: 110,
    source_event_id: 10,
    amount_minor: 1500,
    currency: "SGD",
    occurred_at_utc: weekAgo,
    status: "needs_review",
    description: "Unknown charge",
    text_raw: "some random charge",
    r2_object_key: null,
    needs_review_reason: true,
    message_type: "text" as const,
    transcript: null,
    tags: "[]",
  },
];

export const MOCK_TAGS = [
    "bills", "coffee", "entertainment", "food", "groceries",
    "health", "lunch", "rent", "shopping", "transport",
];
