import type { ExpenseWithDetails } from "./types";

const now = new Date();
const today = now.toISOString();
const yesterday = new Date(now.getTime() - 86400000).toISOString();
const twoDaysAgo = new Date(now.getTime() - 2 * 86400000).toISOString();
const threeDaysAgo = new Date(now.getTime() - 3 * 86400000).toISOString();
const fiveDaysAgo = new Date(now.getTime() - 5 * 86400000).toISOString();
const weekAgo = new Date(now.getTime() - 7 * 86400000).toISOString();

export const MOCK_EXPENSES: ExpenseWithDetails[] = [
  {
    id: 101,
    source_event_id: 1,
    amount_minor: 1850,
    currency: "SGD",
    occurred_at_utc: today,
    status: "final",
    text_raw: "lunch at hawker center",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "Lunch at hawker center",
    category: "Food",
    tags: '["lunch","work"]',
  },
  {
    id: 102,
    source_event_id: 2,
    amount_minor: 3200,
    currency: "SGD",
    occurred_at_utc: today,
    status: "needs_review",
    text_raw: "grab to office",
    r2_object_key: null,
    needs_review_reason: true,
    parsed_description: "Grab to office",
    category: "Transport",
    tags: '["commute"]',
  },
  {
    id: 103,
    source_event_id: 3,
    amount_minor: 5500,
    currency: "SGD",
    occurred_at_utc: yesterday,
    status: "final",
    text_raw: "dinner with friends",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "Dinner with friends",
    category: "Food",
    tags: '["dinner","social"]',
  },
  {
    id: 104,
    source_event_id: 4,
    amount_minor: 12900,
    currency: "SGD",
    occurred_at_utc: yesterday,
    status: "final",
    text_raw: null,
    r2_object_key: "receipts/104.jpg",
    needs_review_reason: false,
    parsed_description: "Uniqlo t-shirts",
    category: "Shopping",
    tags: '["clothing"]',
  },
  {
    id: 105,
    source_event_id: 5,
    amount_minor: 2400,
    currency: "SGD",
    occurred_at_utc: twoDaysAgo,
    status: "final",
    text_raw: "mrt top up",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "MRT top up",
    category: "Transport",
    tags: "[]",
  },
  {
    id: 106,
    source_event_id: 6,
    amount_minor: 150000,
    currency: "SGD",
    occurred_at_utc: threeDaysAgo,
    status: "final",
    text_raw: "rent march",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "Rent - March",
    category: "Housing",
    tags: '["rent","monthly"]',
  },
  {
    id: 107,
    source_event_id: 7,
    amount_minor: 4500,
    currency: "SGD",
    occurred_at_utc: threeDaysAgo,
    status: "final",
    text_raw: "movie tickets",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "Movie tickets",
    category: "Entertainment",
    tags: '["movies"]',
  },
  {
    id: 108,
    source_event_id: 8,
    amount_minor: 8500,
    currency: "SGD",
    occurred_at_utc: fiveDaysAgo,
    status: "final",
    text_raw: "clinic visit",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "GP clinic visit",
    category: "Health",
    tags: '["medical"]',
  },
  {
    id: 109,
    source_event_id: 9,
    amount_minor: 3800,
    currency: "SGD",
    occurred_at_utc: weekAgo,
    status: "final",
    text_raw: "grocery run",
    r2_object_key: null,
    needs_review_reason: false,
    parsed_description: "Grocery run at FairPrice",
    category: "Food",
    tags: '["groceries"]',
  },
  {
    id: 110,
    source_event_id: 10,
    amount_minor: 1500,
    currency: "SGD",
    occurred_at_utc: weekAgo,
    status: "needs_review",
    text_raw: "some random charge",
    r2_object_key: null,
    needs_review_reason: true,
    parsed_description: "Unknown charge",
    category: "Other",
    tags: "[]",
  },
];
